### ISSUE TITLE
Centre and Change the height of instruction page and re-locat the Go Back button

### ISSUE THREAD

**Issue by Nazek-Altayeb** [stephendawsondev/j-day#104]
### Story

As a **player**, I can **read and understand the instructions** so that I can **know how to play the game**.

### Acceptance Criteria

-  instrcution are centered.
-  **Go Back** button is at the bottom left corner

### Tasks

- Resize the instrcution page.
- change the position of the **Go Back** button
- change all the UI text color to Yellow; that includes the game page, welcome page as well

**Comment by stephendawsondev** [comment]
@Nazek-Altayeb I'm closing this as done as it looks like the PR has been merged.
