### ISSUE TITLE
README - Add pinned resources from Slack

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#26]
There's a number of resources pinned in Slack that need to be added to the Readme.

The resources need screenshots and the URLs should be referenced.

Each resource should fit into some sort of category (e..g Planning, Design, Assets, etc.) - whoever takes this task can decide.

We shouldn't omit any resource because even if it wasn't used in the final project, it was still used in the planning stages.

**Comment by stephendawsondev** [comment]
There might be some to go into the *Credits* and *Tech* section of the readme.

**Comment by Markyjay** [comment]
Ill give a go at this today, ill do what i can at least
