### ISSUE TITLE
Project Page - Update Hackthon app project page

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#28]
You can find the project page here: https://hackathon.codeinstitute.net/teams/341/

The team name (Terminalators), project name and project details should be added here. You may want to collab with whoever's looking after the readme tasks.

**Comment by Markyjay** [comment]
Ill put in what i can on the code institute page. Ill use the logo i designed for our team. Ill incorporate the details we have commited to date at least.

**Comment by Markyjay** [comment]
All that is left is the github repo and the deployed site.

**Comment by stephendawsondev** [comment]
Looks like @Markyjay has done this too
