### ISSUE TITLE
README - Add team member details

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#32]
We need to add the LinkedIn Profile and Github profile of each team member. The Github will already have been shared in the Slack channel, but we'll need to ask each person for their LinkedIn. 

Once we have them, add their profile picture, name, LinkedIn and GitHub to the readme.

**Comment by Markyjay** [comment]
I have added some of the names and info already.

**Comment by Markyjay** [comment]
Ive left a section for rachael but can you review and see if whats there is ok?

**Comment by Markyjay** [comment]
Since rachael left ive completed this story
