### ISSUE TITLE
User story - Pause menu

### ISSUE THREAD

**Issue by Markyjay** [stephendawsondev/j-day#54]
### Story

As a player, I can press esc so that I can pause the game..

### Acceptance Criteria

- Pressing esc stops the game sprites in position.
- When pressing esc a transparent screen appears showing interactive buttons resume and quit.
- Resume and quit buttons work as intended on pause screen.

### Tasks

- Create a sprite of pause menu
- pause menu reacts to esc button and stops game play
- apply code to pause menu sprite for resume and quit buttons

**Comment by stephendawsondev** [comment]
It looks like this one has already been added in #36 . Closing this one as a duplicate
